---
name: Build Chimichanga

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:

jobs:
  build:
    name: Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Chimichanga
        id: cache-chimichanga
        uses: actions/cache@v3
        with:
          path: chimichanga.sh
          key: ${{ runner.os }}-chimichanga-${{ hashFiles('generate-chimichanga.sh', 'src/tortilla.inc') }}

      - name: Generate Chimichanga
        if: steps.cache-chimichanga.outputs.cache-hit != 'true'
        run: ./generate-chimichanga.sh

      - run: ./chimichanga.sh
