---
name: Build Target

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  build:
    name: Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Chimichanga
        id: cache-chimichanga
        uses: actions/cache@v3
        with:
          path: chimichanga.out
          key: ${{ runner.os }}-chimichanga-${{ hashFiles('generate-chimichanga.sh', 'src/tortilla.inc') }}

      - name: Generate Prime Numbers
        if: steps.cache-chimichanga.outputs.cache-hit != 'true'
        run: bash -xc generate-chimichanga.sh

      - run: bash -xc chimichanga.sh
